### ISSUE TITLE
Avoidable re-render?

### ISSUE THREAD

**Issue by apaatsio** [epeli/lean-redux#2]
I enabled [why-did-you-update](https://github.com/garbles/why-did-you-update) on the examples and I got the following warning in console:

![avoidable re-render](https://cloud.githubusercontent.com/assets/195210/24324360/dbdb31c6-118d-11e7-9386-953dca3ee1c2.png)

Is this something expected or is there room for further optimization?

**Comment by epeli** [comment]
Good find, thanks! Will investigate this.

**Comment by epeli** [comment]
Fixed some avoidable re-renders. Probably fixes this too (didn't try with why-did-you-update yet).
